yarnPath: .yarn/releases/yarn-3.1.1.cjs
nodeLinker: node-modules
packageExtensions:
  "@firebase/analytics-compat@*":
    peerDependencies:
      "@firebase/app": "*"

  "@firebase/app-check-compat@*":
    peerDependencies:
      "@firebase/app": "*"

  "@firebase/auth-compat@*":
    peerDependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"

  "@firebase/database@*":
    peerDependencies:
      "@firebase/app-types": "*"

  "@firebase/firestore-compat@*":
    peerDependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"

  "@firebase/database-compat@*":
    peerDependencies:
      "@firebase/app-types": "*"

  "@firebase/functions@*":
    peerDependencies:
      "@firebase/app-types": "*"

  "@firebase/functions-compat@*":
    peerDependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"

  "@firebase/messaging-compat@*":
    peerDependencies:
      "@firebase/app": "*"

  "@firebase/performance-compat@*":
    peerDependencies:
      "@firebase/app": "*"

  "@firebase/remote-config-compat@*":
    peerDependencies:
      "@firebase/app": "*"

  "@firebase/storage-compat@*":
    peerDependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"

  eslint-config-react-app@*:
    dependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"

  react-dev-utils@*:
    dependencies:
      typescript: "*"
      webpack: "*"

  react-scripts@*:
    dependencies:
      autoprefixer: "*"
